<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table("users")->insert([
            [
                "sNumber" => "s0770611",
                "name" => "John Doe",
                "email" => "johndoe22@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 1,
            ],
            [
                "sNumber" => "s6052883",
                "name" => "John Smith",
                "email" => "johnsmith32@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 1,
            ],
            [
                "sNumber" => "s2130071",
                "name" => "Jane Austen",
                "email" => "janeausten41@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 1,
            ],
            [
                "sNumber" => "s4367896",
                "name" => "Sarah Lawson",
                "email" => "sarahlawson@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 1,
            ],
            [
                "sNumber" => "s5172118",
                "name" => "Wynnie Mingasson",
                "email" => "wmingasson0@hud.gov",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7669622",
                "name" => "Cindie Fosken",
                "email" => "cfoskenc@weebly.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7523239",
                "name" => "Misha Gerish",
                "email" => "mgerishg@gnu.org",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4367895",
                "name" => "Mei Scriver",
                "email" => "mscriverl@uol.com.br",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321001",
                "name" => "Liam Jacobs",
                "email" => "ljacobs@gmail.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321002",
                "name" => "Sophia Nguyen",
                "email" => "snguyen@yahoo.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321003",
                "name" => "Oliver Turner",
                "email" => "oturner@uol.edu",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321004",
                "name" => "Ava Thompson",
                "email" => "athompson@outlook.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321005",
                "name" => "Noah Walker",
                "email" => "nwalker@hotmail.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321006",
                "name" => "Emily Garcia",
                "email" => "egarcia@icloud.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321007",
                "name" => "James King",
                "email" => "jking@live.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321008",
                "name" => "Amelia Scott",
                "email" => "ascott@gmail.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321009",
                "name" => "Lucas Evans",
                "email" => "levans@uol.edu",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4321010",
                "name" => "Mia Adams",
                "email" => "madams@yahoo.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s9837201",
                "name" => "Alex Martin",
                "email" => "alex.martin@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2325802",
                "name" => "Isabella Perez",
                "email" => "isabella.perez@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6739015",
                "name" => "Benjamin Roberts",
                "email" => "benjamin.roberts@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s1198327",
                "name" => "Emma Lee",
                "email" => "emma.lee@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2410023",
                "name" => "Ethan Harris",
                "email" => "ethan.harris@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6400295",
                "name" => "Charlotte Clark",
                "email" => "charlotte.clark@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7500296",
                "name" => "Henry Lewis",
                "email" => "henry.lewis@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4192930",
                "name" => "Sophia Martinez",
                "email" => "sophia.martinez@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s5320198",
                "name" => "Elijah Young",
                "email" => "elijah.young@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s3298712",
                "name" => "Ella Anderson",
                "email" => "ella.anderson@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2093725",
                "name" => "Mason Hall",
                "email" => "mason.hall@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6203417",
                "name" => "Harper Davis",
                "email" => "harper.davis@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7401243",
                "name" => "William Moore",
                "email" => "william.moore@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s9145678",
                "name" => "Avery Taylor",
                "email" => "avery.taylor@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s1043209",
                "name" => "James White",
                "email" => "james.white@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s8043210",
                "name" => "Lily Jackson",
                "email" => "lily.jackson@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2031485",
                "name" => "Oliver Green",
                "email" => "oliver.green@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s1342904",
                "name" => "Emily Adams",
                "email" => "emily.adams@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2198345",
                "name" => "Liam Nelson",
                "email" => "liam.nelson@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4192038",
                "name" => "Ava Campbell",
                "email" => "ava.campbell@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s5340092",
                "name" => "Daniel Mitchell",
                "email" => "daniel.mitchell@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7309014",
                "name" => "Abigail Carter",
                "email" => "abigail.carter@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s9012345",
                "name" => "Alexander Reed",
                "email" => "alexander.reed@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s3071826",
                "name" => "Ella Sanders",
                "email" => "ella.sanders@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s4092836",
                "name" => "Jackson Phillips",
                "email" => "jackson.phillips@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6019284",
                "name" => "Grace Evans",
                "email" => "grace.evans@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2049583",
                "name" => "Jacob Turner",
                "email" => "jacob.turner@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6592840",
                "name" => "Sofia Rivera",
                "email" => "sofia.rivera@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s7483925",
                "name" => "Logan Stewart",
                "email" => "logan.stewart@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s2341785",
                "name" => "Zoe Powell",
                "email" => "zoe.powell@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s5893174",
                "name" => "Owen Patterson",
                "email" => "owen.patterson@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
            [
                "sNumber" => "s6234509",
                "name" => "Madison Cooper",
                "email" => "madison.cooper@example.com",
                "password" => bcrypt("12345678"),
                "isInstructor" => 0,
            ],
        ]);
    }
}
